export const kenyanCounties = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
];

export const milkProducts = [
  {
    name: "Milk",
    image: "/categories/milk.jpg",
    slug: "milk",
    priceUnit: "Per Litre",
  },
  {
    name: "Yoghurt",
    image: "/categories/yoghurt.jpg",
    slug: "yoghurt",
    priceUnit: "Per Litre",
  },
  {
    name: "Cheese",
    image: "/categories/cheese.jpg",
    slug: "cheese",
    priceUnit: "Per Kg",
  },
  {
    name: "Butter",
    image: "/categories/butter.jpg",
    slug: "butter",
    priceUnit: "Per Kg",
  },

  {
    name: "Ice Cream",
    image: "/categories/ice-cream.jpg",
    slug: "ice-cream",
    priceUnit: "Per Litre",
  },
  {
    name: "Milk Powder",
    image: "/categories/powder.jpg",
    slug: "powder",
    priceUnit: "Per Kg",
  },
];
